### ISSUE TITLE
Some Finnish mobile numbers are formatted wrong

### ISSUE THREAD

**Issue by jlehikoi** [joost/phony_rails#107]
Adding the line 

`expect("04575700834".phony_formatted(:normalize => :FI, :format => :international)).to eql('+358 45 757 00 834')`

to the it "should phony_format" block (within the describe block "with normalize option", "the phony_formatted method", "phony_format String extension", after line 48) creates a minimal failing example. The Finnish mobile number above is interpreted as a Danish number, and it gets added a +45 country code (Denmark).

**Comment by joost** [comment]
See my commit. Not sure if it can be fixed or that the number simply can't be determined as being from Denmark or Finland. PR with fix welcome :)

**Comment by joost** [comment]
Please reopen with PR if needed.
