### ISSUE TITLE
Consider dropping the dependency on the countries gem and using a YAML file instead

### ISSUE THREAD

**Issue by monfresh** [joost/phony_rails#108]
From what I can tell, the only thing you need the countries gem for is for the `country_code` numerical value. I just ran a memory benchmark on my app using the [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) gem, and `phony_rails` is by far the biggest consumer of memory at around 25MB. Most of that is coming from the `countries` gem, which in turn comes from the `currencies` gem. I've asked the `countries` gem maintainer to consider removing `currencies` as a dependency since not everyone will need it. For example, phony_rails doesn't need it, but it still gets required and consumes memory.

Since all you need is a list of numerical country codes, I propose that you create a YAML file based on [the ones in the countries gem](https://github.com/hexorx/countries/tree/master/lib/data/countries), but with only the `country_code` field.

Thoughts? I'd be happy to submit a PR.

**Comment by joost** [comment]
Merged PR (https://github.com/joost/phony_rails/pull/109).

**Comment by joost** [comment]
Will create a new gem version after my holiday :)
