### ISSUE TITLE
Can i skip a validation with another number?

### ISSUE THREAD

**Issue by fabiancarlos** [joost/phony_rails#110]
I want to skip the validation if number is like, '0800', a common number here in Brazil. How is the way to do it?

**Comment by mhink** [comment]
So, Rails will let you do conditional validations based on the return value of a Proc.

http://guides.rubyonrails.org/v3.2.13/active_record_validations_callbacks.html#using-a-proc-with-if-and-unless

So, something similar to this:
```
validate :phone_number, :phony_plausible => true, :unless => Proc.new { |your_model| your_model.should_skip_validation? }
```

**Comment by joost** [comment]
Yep. @mhink 's solution is the way to go.
