### ISSUE TITLE
Correct phone number failed the validatiton

### ISSUE THREAD

**Issue by EveDreamer** [joost/phony_rails#115]
Hi,
I set a variable named `mobile` whose value is `13464359857`. It is a correct formatted phone number in China. But it could not pass the validation after I did `mobile = PhonyRails.normalize_number(mobile, country_code: 'CN')`, the validation `Phony.plausible?(mobile)` will return `false`. 
But if I do not format the  original phone number with PhonyRails, `Phony.plausible?(mobile)` will return `true`. 
Is this a phony_rails issue or phony issue? Thank you!

**Comment by joost** [comment]
The country code for CN is +86 according to our data.
```
irb(main):011:0> m = PhonyRails.normalize_number(mobile, country_code: 'CN')
=> "+8613464359857"
```
So the above should be a valid China number?

I think otherwise Phony will think it is a +1 (US) number.

**Comment by EveDreamer** [comment]
Yes, `"+8613464359857"` is a **valid** China mobile number, `"13464359857"` was formatted by PhonyRails correctly. I was just confused that why `"13464359857"` could pass Phony's validation while `"+8613464359857"` could not. Now I know it is a Phony issue. And I will check the source code of Phony. Thank you for your help and sorry for the late reply.

**Comment by joost** [comment]
So I guess this can be closed.
