### ISSUE TITLE
French formatting

### ISSUE THREAD

**Issue by Apokly** [joost/phony_rails#121]
Hi

I have a bug with french formatting :

```ruby
"06-12-34-56-78".phony_normalized(default_country_code: 'FR') # gives me "+33612345678", good
```

but
```ruby
"06-87-73-83-58".phony_normalized(default_country_code: 'FR') # gives me "+687738358", wrong
```

The only difference is the phone number. The default formatting is the same
Is there a bug or is it my bad ?

Same for "06-24-24-02-48", "04-68-50-11-99", "06-22-36-22-84"

Note that if I force the country code, like
```ruby
"06-87-73-83-58".phony_normalized(country_code: 'FR') # "+33687738358"
```
It works (gives me "+33687738358")

Thank you.

**Comment by joost** [comment]
Duplicates #95.

**Comment by joost** [comment]
Please see that issue. Will push a fix in a minute.

**Comment by Apokly** [comment]
Thank you for the bug fix ! Helped a lot :)
