### ISSUE TITLE
Can it validate mobile phone?

### ISSUE THREAD

**Issue by emn178** [joost/phony_rails#122]
Hi,

as title, can it validate mobile phone only in model?

thanks.

**Comment by joost** [comment]
Unclear what issue is here.

**Comment by emn178** [comment]
I mean that only allow mobile format.

**Comment by Apokly** [comment]
@emn178 You can validate phone number through model validation like :
```ruby
validates_plausible_phone :phone_number
```
https://github.com/joost/phony_rails#validation

or just convert your phone number through :
```ruby
PhonyRails.normalize_number('some number', country_code: 'NL')
```
https://github.com/joost/phony_rails#general-info

Where do you want to "validate" elsewhere than in a model ?

**Comment by waghanza** [comment]
@Apokly have you found any solution ?

**Comment by Apokly** [comment]
@waghanza Haven't use this library for a while but still use it according to my previous comment.

**Comment by joost** [comment]
If you want to **only** allow mobile numbers:
I would make `phony_rails` validate the number and add a second validation checking if the normalized number is mobile (eg. using a regular expression).

**Comment by waghanza** [comment]
I've made this by using a regexp

+ Validate the string start with 06 / 07 / +336 / +337
+ Validate that the string could be normalized by `PhonyRails`
