### ISSUE TITLE
Split fails when a + is present

### ISSUE THREAD

**Issue by wfried** [joost/phony_rails#123]
When using the split method, I'm finding it necessary to strip off the leading "+", like this
`country_number = Phony.split(self.phone_number.tr('+',''))[0]` 

Since I'm using phony to normalize phone numbers and it's adding a leading +, it seems like split should handle the case where a phone number has a + in it. 

My validation code looks like this:
```
phony_normalize :phone_number, default_country_code: 'US'
validates :phone_number, phony_plausible: { ignore_record_country_code: true, ignore_record_country_number: true }
```

Thanks for your feedback!

**Comment by joost** [comment]
Hi @wfried,
The Phony gem assumes your number is a full number with country code. We differ between those with and without by adding a '+'.
I don't know what `Phony.split` does but feel free to add a `PhonyRails.split` that removes the '+' and fixes your issue. Pull request welcome.
Joost
