### ISSUE TITLE
Invalid number is valid?

### ISSUE THREAD

**Issue by DamirSvrtan** [joost/phony_rails#124]
Hi there,

I've just entered: `00385958826590dasdadasddsad`
and have a validation in my model:

```ruby
  validates :telephone_number, phony_plausible: true
```

It passed. I was wondering, is this suppose to pass?

**Comment by joost** [comment]
Probably if `00385958826590` is correct.

**Comment by DamirSvrtan** [comment]
Yes, the beginning is correct. Shouldn't the gem mark it as invalid because of the letters at the end?

**Comment by joost** [comment]
You could force only numbers using some other validation and a regexp.

**Comment by DamirSvrtan** [comment]
So it let's this pass by design? Why if I may ask?

**Comment by joost** [comment]
Not been thought through. If you would like otherwise (or add a 'strict' option to validations) feel free to create a pull request!

**Comment by DamirSvrtan** [comment]
thnx!
