### ISSUE TITLE
No method find_by_normalized_phone_number

### ISSUE THREAD

**Issue by TechRsch** [joost/phony_rails#125]
I tried this method as recommended in the doc but receive a nomethod error.

**Comment by joost** [comment]
This is just an ActiveRecord method based on the `normalized_phone_number` attribute. The doc just suggests you to store a normalized phone number and then search also by normalizing a number.

**Comment by TechRsch** [comment]
I am using phony_normalize not normalized_phone_number. Is that the problem?

**Comment by joost** [comment]
Add a column to your db like `phone_number_normalized`.
Use something as:

````
phony_normalize :phone_number, as: :phone_number_normalized, default_country_code: 'US'
# or
phony_normalize :phone_number_normalized, default_country_code: 'US'
````

Next you can use `find_by_normalized_phone_number` as documented.
