### ISSUE TITLE
Unexpected result when calling normalize_number multiple times with country_code option

### ISSUE THREAD

**Issue by mbrehin** [joost/phony_rails#126]
When normalizing a phone number with an unexpected length multiple times with ```country_code``` option, the prefix is added each time, which is not the behavior obtained with ```default_country_code```option. 

Here is an example :

```ruby 
phone = '06123456789' # French phone numbers have to be 10 chars long  
phone = PhonyRails.normalize_number(phone, country_code: 'FR') # +336123456789
phone = PhonyRails.normalize_number(phone, country_code: 'FR') # +33336123456789
phone = PhonyRails.normalize_number(phone, country_code: 'FR') # +3333336123456789
```

Using ```default_country_code``` option : 

```ruby 
phone = '06123456789' # French phone numbers have to be 10 chars long  
phone = PhonyRails.normalize_number(phone, default_country_code: 'FR') # +336123456789
phone = PhonyRails.normalize_number(phone, default_country_code: 'FR') # +336123456789
phone = PhonyRails.normalize_number(phone, default_country_code: 'FR') # +336123456789
```

**Comment by joost** [comment]
Thanks for the info. Pull request welcome :)

**Comment by mbrehin** [comment]
I'm working on it, but I'm annoyed by a weird behavior of ```Phony.plausible?``` method. 
Maybe you could help.

Here is one of my tests I ran in my console :

```ruby
Phony.plausible?('+464790909090', cc: '46') # false
```

I think it should be true, not false. Could you confirm that I'm right with this ?
I'd like to rely on ```Phone.plausible?``` for every transformation that I'm trying to apply to a phone number. But in the meantime I just can't.

I'll submit my pull request despite of that problem, but I hope to find a better way to manage and validate that case.

**Comment by joost** [comment]
Hi @mbrehin,

I gave your initial issue report a quick look. It seems `06123456789` is not valid (`Phony.plausible?`). This is why we add the `country_code` number. Actually this behaviour is intended.
We rely on the Phony gem for the plausible method.

Joost

**Comment by mbrehin** [comment]
Hi @joost,

I'm sorry about that, I didn't check the french phone number but focused on the swedich one (the one in your specs : +464790909090). 

Just a last question: don't you think the country prefix shouldn't be added multiple times even if the given phone number is wrong formatted (for instance, the wrong french mobile phone number I used)? Or at least it shouldn't be added at all?

**Comment by joost** [comment]
I agree we should not add them multiple times. Pull request welcome for that one :)
