### ISSUE TITLE
invalid number assumed to be valid

### ISSUE THREAD

**Issue by jacek213** [joost/phony_rails#130]
`  validates :phone, :phony_plausible => true`

it doesn't yield error for number `303783340360`, which is not valid (check here for example: https://www.twilio.com/lookup)

**Comment by joost** [comment]
Thanks for the input! Can you check if the https://github.com/floere/phony thinks the number is correct/incorrect. It may be an issue for that gem.

**Comment by jacekgrzybowski** [comment]
You're probably right that `phony` would be the one to blame :) Will check later today.
