### ISSUE TITLE
In normalize_number, .clone is being used, which preserves "frozenness", causing method to fail sometimes

### ISSUE THREAD

**Issue by davekapp** [joost/phony_rails#136]
We've been adding `# frozen_string_literal: true` to our files in preparation for the (eventual) move to Ruby using frozen strings by default, and we've encountered some strange behavior in our rspecs from this. As far as I can tell, the issue is that #clone preserves the "frozenness" of a string, causing using `PhonyRails.normalize_number(...)` to fail on a string literal passed in from a spec, even though the method is trying to make changes to a copy.

In my testing at a glance `String#dup` does not preserve the frozen state of a string when making a copy. I'm not sure offhand if there are other ramifications to using dup instead of clone, but in my trials it has worked fine.

This seems like a relatively small change if you're okay with the switch, so I'd be happy to make the changes and do a PR sometime next week.

Thanks for the incredibly useful gem, we're big fans of it. :)

**Comment by joost** [comment]
In v0.13.1. Let me know if it works for you.

**Comment by davekapp** [comment]
Thank you, will update shortly and give it a try!

**Comment by rachel-carvalho** [comment]
I know it's an old issue, but I can confirm that this is now fixed (I've updated `phony_rails` and it works now).
