### ISSUE TITLE
is it necessary to extend ActiveRecord::Base instead of ActiveModel::Model ?

### ISSUE THREAD

**Issue by brandondees** [joost/phony_rails#143]
it appears that currently database-free rails apps cannot use the validation methods, etc. because they are attached to ActiveRecord::Base instead of ActiveModel::Model or ActiveModel::Validations

Is there a reason I'm overlooking? Should I work up a PR?

**Comment by joost** [comment]
PR welcome :)

**Comment by brandondees** [comment]
pr submitted #144
