### ISSUE TITLE
Switching the dependancy from `ActiveRecord::Base` to `ActiveModel::Model` breaks support for Rails 3 apps

### ISSUE THREAD

**Issue by EduardoBautista** [joost/phony_rails#147]
Not sure if this was intentional or not.

**Comment by EduardoBautista** [comment]
Only starting in Rails 4.

**Comment by wvanheerde** [comment]
Running into the same issue now. ActiveModel is only there since Rails 4. Is it possible for you to have a look at this?

**Comment by joost** [comment]
Feel free to fix and send a pull request :)

**Comment by joost** [comment]
v0.14.5
