### ISSUE TITLE
Add support for internal Russian phone style (8 926 ... instead of +7 926 ...)

### ISSUE THREAD

**Issue by petRUShka** [joost/phony_rails#148]
By some historical reasons the internal format for phone numbers is even more popular than the international format! And unfortunately it is completely unsupported by `phony_rails` gem.

For example mobile number in international format '+7 926 1234567' a Russian citizen would likely write down as '8 926 1234567'.

The topic is discussed in Wikipedia article: https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia

So instead of 

```
PhonyRails.normalize_number('8 926 1234567', country_code: 'RU')                                  
=> "+789261234567"
```

There should be something like this

```
PhonyRails.normalize_number('8 926 1234567', country_code: 'RU')                                  
=> "+79261234567"
```

As it have done with '+7'

```
PhonyRails.normalize_number('7 926 1234567', country_code: 'RU')                                  
=> "+79261234567"
```

**Comment by joost** [comment]
Probably check with the https://github.com/floere/phony gem?!

**Comment by petRUShka** [comment]
Ok, I'll create issue there.
