### ISSUE TITLE
Make phony_normalize optional, on condition

### ISSUE THREAD

**Issue by januszm** [joost/phony_rails#149]
If I get it right, calling ```phony_normalize :phone_attribute``` in a Rails model definition basically sets callback:

```ruby
before_validation do
  set_phony_normalized_numbers(attributes, options)
end
```

This is all fine but unfortunately it seems that it makes erasing the phone number impossible (update with empty string or nil). I think that it'd be great if we could call this method with an option like

```phony_normalize :phone_attribute, unless: -> (n) { n.blank? }```

or maybe even better:

```phony_normalize :phone_attribute, allow_blank: true```

We could make a change in ```#set_phony_normalized_numbers``` or ```normalize_number```.  Something like 

```
+++ b/lib/phony_rails.rb
@@ -50,7 +50,7 @@ module PhonyRails
-    return if number.blank?
+    return '' if number.blank?
```

or a bit more complex solution:

```ruby
if number.blank?
  return options[:allow_blank] ? '' : nil
end
```

**Comment by bdewater** [comment]
Came across a similar issue today. `before_validation` (via [`set_callback`](http://api.rubyonrails.org/classes/ActiveSupport/Callbacks/ClassMethods.html#method-i-set_callback)) already accepts `:if`, `:unless` and `:prepend` options. So you should be able to do:

```
before_validation unless: -> { n.blank? } do
  set_phony_normalized_numbers([:phone_attribute], options)
end
```

**Comment by januszm** [comment]
But I'd need to patch https://github.com/joost/phony_rails/blob/master/lib/phony_rails.rb anyway. Ok maybe I'll prepare a Pull Request for this

**Comment by bdewater** [comment]
I meant you should be able to use that snippet in your model if you're in a hurry (like me). I'm sure a PR is welcome to add passing these options to `set_callback` in the gem itself 😄

**Comment by joost** [comment]
Pull request very welcome :)

**Comment by joost** [comment]
Not sure what you exactly mean. See added specs in https://github.com/joost/phony_rails/commit/94393779b2ac8fac2e6e93b52ef5a1ba8dc2afe1.

**Comment by januszm** [comment]
Wow, that helped a lot. Thank you and I'm sorry about the confusion. I've found another place where request parameter was deleted if it was blank, before it reached the model update method.  It got even more confusing after @bdewater confirmed he had similar issue (it must have been different though)!.
