### ISSUE TITLE
Extension example in README does not work

### ISSUE THREAD

**Issue by derekprior** [joost/phony_rails#155]
From the README:

> Validation supports phone numbers with extension, such as +18181231234 x1234 or '+1 (818)151-5483 #4312' out-of-the-box.

In my app:

```ruby
class Address
  validates :phone_number, phony_plausible: true
  validates :fax_number, phony_plausible: true

  phony_normalize :phone_number, default_country_code: 'US'
  phony_normalize :fax_number, default_country_code: 'US'
end
```

In console:

```ruby
address = Address.new(phone_number: '+18181231234 x1234')
address.valid? # false
address.errors.full_messages # ["Phone number is an invalid number"]
```

**Comment by derekprior** [comment]
It looks like the change that added this functionality is not released on RubyGems. This works if I pull the GitHub version of the gem. Any chance you could push the updated gem to eliminate this confusion?

**Comment by ollym** [comment]
This has now been done, you can close this issue
