### ISSUE TITLE
Invalid number in countryCode VN

### ISSUE THREAD

**Issue by AkaiNNT** [joost/phony_rails#159]
I used: `validates_plausible_phone :phone`
It displays an error for the number "+841628998838" and any "+84162xxxxxxx", but it is valid (check here: https://www.twilio.com/lookup)
Thank you for help!

**Comment by CollinGraves** [comment]
@AkaiNNT I wasn't able to get this to fail. Will you provide a approach to recreate the issue? Seems to be working properly on my end.

CG

**Comment by joost** [comment]
@AkaiNNT can I close this ticket?
