### ISSUE TITLE
Extensions not working out of the box for validator

### ISSUE THREAD

**Issue by estiens** [joost/phony_rails#160]
Model
```
phony_normalize :main_phone, default_country_code: 'US'
validates :main_phone, phony_plausible: true
```

Console
```
pry(main)> contact = Contact.new(first_name: 'John', last_name: 'Doe', 
address_1: '123 Main St', city: 'Minneapolis', state: 'MN', 
zip: '55405', main_phone: '612-555-1212')

pry(main)> contact.save
=> true

pry(main)> contact.main_phone
=> "+16125551212"

pry(main)> contact = Contact.new(first_name: 'John', last_name: 'Doe', 
address_1: '123 Main St', city: 'Minneapolis', state: 'MN', 
zip: '55405', main_phone: '612-555-1212 x123')

pry(main)> contact.save
=> false

pry(main)> contact.errors.messages
=> {:main_phone=>["is an invalid number"]}

pry(main)> contact.main_phone
=> "+16125551212 x123"
```

**Comment by CollinGraves** [comment]
@joost any thoughts here? I've been poking around a bit and was able to validate @estiens issue. Definitely happening within call to `Phony#plausible?`

**Comment by trcarden** [comment]
+1

**Comment by joost** [comment]
Open for suggestions :)

**Comment by trcarden** [comment]
Use the extension compatible plausible call in this gem `plausible_number?` (which delegates to `Phony.plausible?`) in the validator. Since the extension feature was something this gem introduced and not `Phony` I think that would be my suggestion

**Comment by trcarden** [comment]
@joost took a look and my issue (which may have been slightly different than @estiens ) was just a version error combined with forgetting to disable/restart spring. After upgrading to `0.14.5` validations passed for numbers with extensions (just as your tests say they should).
