### ISSUE TITLE
Croatian number not validating as plausible.

### ISSUE THREAD

**Issue by pzupan** [joost/phony_rails#165]
Phony 2.15.45 properly normalizes and validates this Croatian number:

```
main:0> Phony.normalize "+385 98 352 085"
=> "38598352085"
main:0> Phony.plausible? "+385 98 352 085"
=> true
```

But this test fails in phony_rails 0.14.4:

```
CROATIA_NUMBER_WITH_COUNTRY_CODE = '385 98 352 085'.freeze
context 'when a country code is passed as a symbol' do
      before(:each) do
        @home = SymbolizableHelpfulHome.new
      end

      it "should validate a valid number with the right country code" do
        @home.phone_number = CROATIA_NUMBER_WITH_COUNTRY_CODE
        @home.phone_number_country_code = 'HR'
        expect(@home).to be_valid
      end
end
```

Note that 385 98 352 0850 [not a valid number] validates as plausible.

**Comment by joost** [comment]
@pzupan pull request would be welcome.

**Comment by pzupan** [comment]
Trying to get time to do that...

**Comment by davidkovsky** [comment]
I see the same behavior with a Russian number. Phony 2.15.49 says it's plausible. Phony_rails 0.14.6 says it isn't. I'll try to make some time this week to investigate.

**Comment by davidkovsky** [comment]
Update: I had forgotten about the interaction between the validator and the `country_code` column. We have a new use case where those might not match. I'll just make a custom validator that asks `Phony.plausible?(number)` in order to get around the mismatch.
