### ISSUE TITLE
0.4.11 was the latest release. However the new normalize_when_valid has been sitting here for a while... Release?

### ISSUE THREAD

**Issue by dlikhten** [joost/phony_rails#194]
Wanted to know if we can get a 0.4.12 soon and use the `normalize_when_valid` feature. Anything holding it up? Looks like its been sitting there for half a year now.

Also to note, the docs (README) do show the new behavior, but the latest package doesn't have that behavior.

**Comment by joost** [comment]
Done, see v0.4.12.

**Comment by dlikhten** [comment]
<3
