### ISSUE TITLE
support for arrays in postgres

### ISSUE THREAD

**Issue by holden** [joost/phony_rails#59]
We store emails & phone numbers in arrays rather than in simple fields and use something like this to validate the array's attributes.

https://gist.github.com/ssimeonov/6519423

Which I'm attempting to use like so:

`validates :phones, enum: { phony_plausible: true }`

This works for other kinds of attributes but I can't get it to work with your gem.

I get the error

`element 0 (7534721234) is an invalid number`

However if I try `447534721234` it works fine.

I also double check that it worked on a single column and it worked fine.  Any idea how I could fix this?

Thanks,

**Comment by joost** [comment]
Guess it is an invalid number? :)
