### ISSUE TITLE
PhonyRails.normalize_number is removing unexpected zero 

### ISSUE THREAD

**Issue by parasharrk** [joost/phony_rails#77]
PhonyRails.normalize_number('09303112459') => 933112459

I am expecting '9303112459'

Not sure why this method is removing zero('0') following by '3'.

**Comment by joost** [comment]
+93 is Afghanistan right?
Guessing 93 is a country number the phony gem automatically removes the '0' after that number since you tent to leave that out. At least in The Netherlands. Eg. +31 (0) 10 1234 123 becomes '31101234123'.

**Comment by kylesziv** [comment]
I feel that this should be in the documentation. This introduced a pretty big bug into our system.

**Comment by joost** [comment]
Pull request welcome :)

**Comment by kylesziv** [comment]
Will do :dancer:
