### ISSUE TITLE
Phone numbers with extensions

### ISSUE THREAD

**Issue by jdel** [joost/phony_rails#78]
I tried to use phony_rails a few minutes ago and I run into a problem validating phone numbers containing extensions.

Let's say my base phone number (in Luxembourg) is +352 123 456
This will be followed by 3 digits extensions, for example +352 123 456 777 is a valid number here but it fails to validate. +352 123 456 1 fails to validate too, even if it is a valid number, however, +352 123 456 77 works fine.

Are there any options to skip the length validation part of the numbers as this seems to be the issue ?

**Comment by joost** [comment]
See #57. No options to skip yet. I guess there is no extension support in Phony. Pull request welcome :)

**Comment by jdel** [comment]
If i can find time to clear my own issues I might have a look at this :) Thanks.

**Comment by joost** [comment]
Closing for now.. PR welcome :)
