### ISSUE TITLE
Method phony_formatted return "undefined method `split' for 1:Fixnum"

### ISSUE THREAD

**Issue by acaron** [joost/phony_rails#79]
Here is a screenshot from the console:
![screen shot 2015-03-02 at 13 01 16](https://cloud.githubusercontent.com/assets/1609917/6446966/d5c6e0cc-c0dc-11e4-90b1-b9738ed66e55.png)

It should be returning `nil` or throwing an error in that case (depends on the behavior you want). I don't really know about every phone number possible but someone entered "8887716095" and it was wrong. He probably wanted: +1 888-771-6095 so it should work!

**Comment by joost** [comment]
If you expect the input string to be unnormalized use:

    "8887716095".phony_formatted(format: :international, normalize: 'US') # => "+1 888 771 6095"

Also the latest version has a explicit `:raise` option, eg:

    "8887716095".phony_formatted(format: :international, raise: true) # will raise the error you mentioned.
