### ISSUE TITLE
Allow validating against multiple countries

### ISSUE THREAD

**Issue by artmees** [joost/phony_rails#81]
currently I can't figure out if it's possible to validate the `country_code` of a `phone_number` to be one of multiple country codes...

for example I was thinking
```rb
  # assume that by default the number is from US but allow numbers also from GB
  validates_plausible_phone :phone_number, country_code: ["GB", "US"]
  phony_normalize :phone_number, default_country_code: 'US'
```
so that I could validate if the number is a valid number in either the US or GB
but I'm not sure if that is possible under the current implementation or not

**Comment by joost** [comment]
Currently not possible. Pull request welcome!

**Comment by artmees** [comment]
Will try to do it in my free time
