### ISSUE TITLE
Simple question about creating a record

### ISSUE THREAD

**Issue by davidtlee** [joost/phony_rails#83]
Assuming I follow the README, am I supposed to be able open the rails console (`rails c`) and execute
```
User.first.update_attribute :phone_number, '<some phone string>'
```
and phony_rails will automatically normalize the string and save it into the table?

I seem to be missing something because no normalization is happening. Moreover, if I give it a clearly wrong phone number, e.g. `User.first.update_attribute :phone_number, '1111'`, the commit is still successful.

In app/models/user.rb, I have:

```
  phony_normalize :phone_number, :default_country_code => 'US'
  validates :phone_number, phony_plausible: true
```
Thanks!

**Comment by joost** [comment]
u = User.first
    u.phone_number = '1111'
    u.save # gets normalized

**Comment by davidtlee** [comment]
Ahhh, thanks @joost!
