### ISSUE TITLE
Validate a phone number format, but don't require the presence

### ISSUE THREAD

**Issue by davidtlee** [joost/phony_rails#84]
I want to ensure that if a phone number is set, it should be a valid phone number. However, when I use the given validation, it also requires there to be a phone number. Is there a simple way to do this? Thanks!

**Comment by joost** [comment]
Probably use `:allow_blank`. Please use Github issues for issues. Not questions (try stackoverflow for those).

**Comment by davidtlee** [comment]
Got it, sorry about that! (I asked here cause some other repos I used had that practice)
