### ISSUE TITLE
Somethign wrong with normalization of NO phones

### ISSUE THREAD

**Issue by uzzer** [joost/phony_rails#85]
PhonyRails.normalize_number("47386160", default_country_code: 'NO').should eq('+4747386160')

I will deal with it, just want to have an issue code in main repo.

**Comment by uzzer** [comment]
Issue closed. Sad that request was not merged but taken as part of another not related commit, but still good to know that it is added to master so fast.

**Comment by joost** [comment]
@uzzer my bad. But still thanks! :)
