### ISSUE TITLE
Some numbers not normalizing properly as of 0.12.1

### ISSUE THREAD

**Issue by webandtech** [joost/phony_rails#87]
Looks like a change causes some numbers to normalize incorrectly.

0.12.0
```
PhonyRails.normalize_number('2318725305', default_country_code: 'US')
 => "+12318725305"
```

0.12.1
```
PhonyRails.normalize_number('2318725305', default_country_code: 'US')
 => "+2318725305"
```

**Comment by joost** [comment]
Seems to come from https://github.com/joost/phony_rails/pull/86. @uzzer care to take a look?

**Comment by joost** [comment]
Seems like the phony gem thinks `2318725305` is a valid number (for a country with +2 or +23 or something) and thus we do not add a +1 (since it thinks we already have a country number).

Not sure what is correct and if phony is wrong?!

**Comment by webandtech** [comment]
The behavior I would hope for is that phony would try to validate the number by adding the default country code (if specified) first if it does not begin with it already. If that fails, then try assuming the country code was already there?

**Comment by joost** [comment]
Good idea. This is in v0.12.2.

**Comment by joost** [comment]
In v0.12.3:

          PhonyRails.normalize_number('2318725305', country_code: 'US').should eq('+12318725305')
          PhonyRails.normalize_number('2318725305', default_country_code: 'US').should eq('+12318725305')
          PhonyRails.normalize_number('+2318725305', default_country_code: 'US').should eq('+2318725305')

**Comment by nathansamson** [comment]
Should this also not look for double zero's (eg 00324980000, default_country_code: 'US' => '+3249800000')

**Comment by nathansamson** [comment]
Also
      PhonyRails.normalize_number('02318725305', default_country_code: 'US').should eq('+12318725305') which I believe is currently not the case

**Comment by joost** [comment]
If `02318725305` is a valid US number it should. Same for `0032` case. Might be logical. Anyways.. PR welcome :)
