### ISSUE TITLE
Does not normalize when validations are skipped

### ISSUE THREAD

**Issue by nathansamson** [joost/phony_rails#88]
This might be a uncommon use case, but I have an import function (via excel/csv sheets).

If the object (lets call it ContactPerson) is not valid (eg misses fields etc...) I want to be able to use contact_person.save(validate: false), but if it contains a mobile number still have it normalized.

This is currently not the case.

Note that I probably should override my presence validators when importing, instead of skipping ALL validations, but still I find it unexpected that phony_normalize runs before_validation, instead of before_save, or even on the setter.

Although I am not sure what I expect it to do when the number can not be normalized (eg, is invalid)...

My current proposal is
A) normalize the number in before_save
B1) if the number is not valid, just store the value as if (if validations are skipped)
B2) if the number is valid just store the normalization.

This is the most backwards compatible, without breaking most existing expectations. Although it isn't really the least suprise either.

My main concern is that when not running validations, numbers are not normalized which ruins my search methods....

Hoping this makes a little sense, as I am quite confused myself :)

**Comment by joost** [comment]
Special cast. Just write your own `before_filter` that uses `PhonyRails.normalize`.
Otherwise please submit a pull request.
