### ISSUE TITLE
phony_normalize strips parentheses from NDC part

### ISSUE THREAD

**Issue by brentahiti** [joost/phony_rails#89]
when validating this number '+33 (0)6 87 36 18 75' (French number), which is valid from Phony.plausible?, phony_normalize strips the parentheses here : https://github.com/joost/phony_rails/blob/master/lib/phony_rails.rb#L25.
The resulting number ('+330687361875') isn't plausible anymore

**Comment by joost** [comment]
Closed by https://github.com/joost/phony_rails/commit/5a18f73ab873c6e28bba3c3b50cf0b8aa28671d2. Also added tests.

**Comment by joost** [comment]
Is in v0.12.4.
