### ISSUE TITLE
activerecord dependency

### ISSUE THREAD

**Issue by sbounmy** [joost/phony_rails#99]
Hello,

Any valid reason ```active_record``` is required here ?
https://github.com/joost/phony_rails/blob/master/lib/validators/phony_validator.rb#L4

For people using ORM such mongoid it doesnt make sense to require AR.
I believe we could just require ```active_model``` instead.

WDYT ?

Thanks,
Stephane.

**Comment by joost** [comment]
Yep sure. Open for a PR.
